
// search
export const FETCH_SEARCH_HOTDATA = "FETCH_SEARCH_HOTDATA";
export const FETCH_SEARCH_SEARCHDATA = "FETCH_SEARCH_SEARCHDATA";
export const FETCH_SEARCH_TYPESDATA = "FETCH_SEARCH_TYPESDATA"
export const FETCH_SEARCH_FILTERDATA = "FETCH_SEARCH_FILTERDATA"