// search
export const FETCH_SEARCH_HOTDATA = 'FETCH_SEARCH_HOTDATA'
export const FETCH_SEARCH_SEARCHDATA = 'FETCH_SEARCH_SEARCHDATA'
export const FETCH_SEARCH_TYPESDATA = 'FETCH_SEARCH_TYPESDATA'
export const FETCH_SEARCH_FILTERDATA = 'FETCH_SEARCH_FILTERDATA'
// cart
export const SET_CART_DATA = 'SET_CART_DATA'
export const ADD_CART_DATA = 'ADD_CART_DATA'
export const DEL_CART_DATA = 'DEL_CART_DATA'
// classcation
export const FETCH_CLASS_LIST = 'ADD_CART_DATA'
export const FETCH_CLASS_GOODS = 'DEL_CART_DATA'
// commet
export const GET_DETAIL_COMMET = 'DEL_CART_DATA'
// home
export const GET_BANNERLIST = 'GET_BANNERLIST'
export const GET_NAVLIST = 'GET_NAVLIST'
export const GET_GOODSLIST = 'GET_GOODSLIST'
export const GET_RECOMLIST = 'GET_RECOMLIST'
// login
export const FETCH_LOGIN_ISLOGIN = 'FETCH_LOGIN_ISLOGIN'
// reg
export const FETCH_REG_ISREG = 'FETCH_REG_ISREG'
export const FETCH_REG_GETCODE = 'FETCH_REG_GETCODE'
export const FETCH_REG_HASHCODE = 'FETCH_REG_HASHCODE'
// shop
export const GET_DETAIL_DETAIL = 'GET_DETAIL_DETAIL'
// size
export const GET_DETAIL_SIZE = 'GET_DETAIL_SIZE'
